### ISSUE TITLE
Documentation improvement and mgo v2 compatibility

### ISSUE THREAD

**Issue by dennypenta** [globalsign/mgo#113]
If you have docs for the project I can add to the github main page and write some description.
I first time see this repo, so what about compatibility with mgov2? Did it save?

**Comment by domodwyer** [comment]
Hi @dennypenta 

The compatibility is maintained yes - this fork is a drop-in replacement of the original mgo. The docs can be found [on GoDoc](https://godoc.org/github.com/globalsign/mgo).

Thanks!
Dom

**Comment by owenhaynes** [comment]
I would only say that interface compatibility is maintained. You can not drop into place over the old v2 without rewriting all your mgo paths.

**Comment by a-pav** [comment]
Hi @domodwyer 
I tried to switch from mgo.v2 to globalsign/mgo for my project but the experience was problematic.
Using globalsign I get "not found" error on a simple .FindId operation while the same operation using mgo.v2 returns the document with no error.
I might not be able to help you thoroughly find what's going wrong here, but; I needed to tell you that globalsign might not be completely compatible with databases previously driven by mgo.v2.
BTW: the error was returned from session.go:3743, because `len(findReply.Cursor.FirstBatch) == 0`
