### ISSUE TITLE
Add interfaces for main queries structures

### ISSUE THREAD

**Issue by dennypenta** [globalsign/mgo#118]
Usually, for unit tests in my projects, I add interface for the Collection and Query structures.

What if we will try to add that interfaces exactly in the driver?
I can implement it.

Additionally, I can implement mocks, because that structures will large.
It would be helpful for a testing not data access layer, controllers for example.

**Comment by szank** [comment]
This have been already considered, and might break backwards compatibility, which we want to avoid.
If someone is derererencing the  Collection or Query pointers for whatever reason, their code won't compile if you switch the mgo return values to interfaces. 

One way to do it is to create a copy of the whole API that uses interfaces, and maintain it alongside the current one. Alas, this is not maintanable IMHO.

**Comment by domodwyer** [comment]
Hi @dennypenta 

Because of the "builder pattern" of having a method returning it's own concrete type I don't think all methods can be mocked without changing the `Query` type itself like @szank says.

I'm of the opinion that clients should implement a small interface defining the methods they use rather than use a big one with all the methods available - keeping interface scope small and local to the caller helps avoid unrelated changes breaking things.

Saying that, if you've got a nice idea of how to do this feel free to open a PR and we'll have a look, just be aware of the above :)

Thanks for the help!
Dom
