### ISSUE TITLE
Dial causing data race

### ISSUE THREAD

**Issue by 2514millerj** [globalsign/mgo#220]
My application is consistently running into a data race after a couple of seconds. I tried both the master and development branches and I am getting the same results. I am also only using a single session, here is my code:

    session, session_err := mgo.Dial(mongo_uri)
    if session_err != nil {
      glog.Error(session_err)
      return
    }
    defer session.Close()

    for {

    }

And the error:

`==================
WARNING: DATA RACE
Read at 0x00c4201bc658 by goroutine 30:
  github.com/globalsign/mgo.(*DialInfo).Copy()
      /go-workspace/src/github.com/globalsign/mgo/session.go:618 +0x104
  github.com/globalsign/mgo.(*mongoCluster).syncServer()
      /go-workspace/src/github.com/globalsign/mgo/cluster.go:206 +0x273
  github.com/globalsign/mgo.(*mongoCluster).syncServersIteration.func1.1()
      /go-workspace/src/github.com/globalsign/mgo/cluster.go:546 +0x215

Previous write at 0x00c4201bc658 by main goroutine:
  github.com/globalsign/mgo.(*Session).SetSocketTimeout()
      /go-workspace/src/github.com/globalsign/mgo/session.go:2197 +0x7a
  github.com/globalsign/mgo.Dial()
     /go-workspace/src/github.com/globalsign/mgo/session.go:317 +0xda
  main.main()
      /go-workspace/src/mqtt-kafka-bridge/bridge.go:179 +0x50b

Goroutine 30 (running) created at:
  github.com/globalsign/mgo.(*mongoCluster).syncServersIteration.func1()
      /go-workspace/src/github.com/globalsign/mgo/cluster.go:518 +0x174
  github.com/globalsign/mgo.(*mongoCluster).syncServersIteration.func1.1()
      /go-workspace/src/github.com/globalsign/mgo/cluster.go:565 +0x368
==================`

**Comment by domodwyer** [comment]
Hi @2514millerj 

What commit is the above stack dump from?

Dom

**Comment by 2514millerj** [comment]
9043a38cb3adad745eeb453c265e8be2c87815c2 -- Development branch

**Comment by 2514millerj** [comment]
I do not get the data race when using DialWithInfo, only using Dial, if that helps clear anything up.

**Comment by tadukurow** [comment]
@2514millerj can you post the dial string you are using? and the dialInfo you use with DialWithInfo?
 
Dial and DialWithTimeout extract the dialInfo options from the URI. DialWithInfo does not.
The race seems to occur when Dial sets the timeouts after calling DialWithInfo, coinciding with the serverSyncLoop copying dialInfo.

**Comment by RO-29** [comment]
Hello @eminano , Looks like I encountered the same bug, I could manage to use `dialWithInfo` for all my projects with my default timeout settings.

But in some apps, I need to `"clone"` the session and use different timeouts and don't want to use `SetSyncTimeout` or `SetSocketTimeout` since apparently, these methods are what causes the data race issue according to your above comment.

Will you accept the PR which implements a function 
```
func (s *Session) CopyWithTimeouts(some timeouts ...) *Session{
  ...
  ...
  ...
}
```
which sets the timeout according to what I want while cloning/ copying
Problem is I don't want to make local changes as I continuously sync the libraries such as mgo in my vendor.

Thank you so much for the wonderful work on this driver 👍
