### ISSUE TITLE
too many goroutine created in mgo?

### ISSUE THREAD

**Issue by tokingHong** [globalsign/mgo#317]
![image](https://user-images.githubusercontent.com/39825820/50630953-95333300-0f7d-11e9-9dfe-762839220680.png)
  Is' so weird !!!!
Under what circumstances will this problem occur?

Normal situation is below
![image](https://user-images.githubusercontent.com/39825820/50631121-37531b00-0f7e-11e9-92b4-404377c3b270.png)

**Comment by domodwyer** [comment]
Hi @tokingHong 

This is totally normal - mgo has an internal connection pool so queries can reuse open connections rather than having to perform the full handshake every time. This lowers latency and is fairly normal - the sockets in your screenshot are waiting in the pool as designed.

Hope this helps!

Dom
