### ISSUE TITLE
func (*Query) Count doesn't accept applySkipLimit parameter

### ISSUE THREAD

**Issue by Tri125** [globalsign/mgo#77]
Ported issue from go-mgo/mgo.

According to the documentation of [mongodb 3.0](https://docs.mongodb.com/v3.0/reference/method/cursor.count/), cursor.count() accept a boolean parameter named "applySkipLimit".

By default, calling cursor.count() will ignore the effects of skip() and limit().
If applySkipLimit is set to true: cursor.count(1), it will consider the effect of skip() and limit().

In mgo, [Query.Count()](https://godoc.org/github.com/globalsign/mgo#Query.Count) doesn't accept a boolean parameter. It will also consider the effects of skip() and limit() by default, which is the opposite of the expected behavior.

**Comment by domodwyer** [comment]
Hi @Tri125 

Thanks for bringing this up, you raise a good point! 

Unfortunately changing the behaviour of `Count()` is definitely a breaking change and would mean we couldn't use this fork as a drop in replacement for the original mgo. It's far from ideal, but I think at this point it's best to keep it as is. If you want to update the documentation to clarify the behaviour we'll happily accept a PR.

Because of this I guess you will have to build your query without the `Skip()`/`Limit()` calls when calling `Count()` to get the behaviour you're after.

Sorry!
Dom

**Comment by miketonks** [comment]
We would also like this behavior.  With a large data set, counting all rows is very slow.  Count with limit can give us a much better response time.

To avoid a breaking change, how about a new function CountSkipLimit() ?
