### ISSUE TITLE
.Select and struct of data

### ISSUE THREAD

**Issue by chneau** [globalsign/mgo#99]
Hello !

I'm not sure if it's a normal behaviour, something to be aware of or a potential improvement. 

Context:
I'm working with AIS data (positions of vessels delimited by time/area), so basically, on my database the document is about 20 fields (a mix of strings, integers and floats).
On my go project (doing stats for vessels) I do a request to get the a list of position/time for a vessel. What I really need here is just 3 fields so my type struct is as simple as Time, location and an integer which is a vessel identifiant. 

Without a ".Select" of the 3 fields of interest :
A run grows up to 3gb in memory. 
![image](https://user-images.githubusercontent.com/5753629/36033932-39bcd42a-0daa-11e8-9a3c-3fda9b284a05.png)

With a ".Select" of the 3 fields of interest (basically the select gets only the 3 fields I described on my struct):
.Select(bson.M{"location": 1, "SOG": 1, "RecvTime": 1})
A run grows up to 700mb (which is the volume of data I expected roughly)
![image](https://user-images.githubusercontent.com/5753629/36033973-5ab67654-0daa-11e8-8151-8e56a8850703.png)

Both runs get the data I need.

What I expect at the start:
My struct only have 3 fields (that I care about) but my database document can have 20 fields.
I thought it would have magically do the Select behind the scene so the database request is already optimised.

What I learned :
It's helpful to do a Select on the find to only get the data that really matters.
It's important to know it especially when you work with partial fields and not all the document.
Adding a select result in both lighter networking, lighter memory footprint, faster execution.

Maybe that's a rookie error, then, my bad tho.

**Comment by domodwyer** [comment]
Hi @chneau 

Thanks for the detailed report!

You raise a good point about using structs with a subset of the document fields. This is because MGO is not an ORM - it does not attempt to provide any mapping beyond getting the query results out. No matter what struct you feed mgo it basically does the equivalent of a `SELECT *` in the background and it's left to the caller to specify the query behaviour.

It's definitely something that will catch people out but it's unlikely we'll change mgo to select the fields required by the struct automatically: it would require reflection over the provided struct during the query phase to figure out what fields to ask for - this would add overhead to each request. To make a proper decision we need to run some benchmarks to quantify the cost, but in the meantime it might be best to update the docs to make this behaviour a bit less surprising!

Thanks - we'll check it out!

Dom
